services:
  housing-price-predictor:
    container_name: housing-price-predictor
    build: ./real-estate-tool-backend
    ports:
      - "8720:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
